apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-lab-node
  namespace: devops-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-lab-node
  template:
    metadata:
      labels:
        app: devops-lab-node
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: app
          image: devops-lab-node:0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 5
